services:
  app:
    build:
      context: .
      dockerfile: modon/Dockerfile
      args:
        - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    env_file:
      - modon/.env
    ports:
      - "8000:8000"
